### PR TITLE
Use raw origin for telemetry

### PR DESCRIPTION
**Pull request by fractalcat**
WIP, do not merge.

Fix bug in telemetry packing wherein the profiler is passed an origin
suffixed with a namespace (e.g., ABCDEF_INTERNAL), which (being longer
than eight bytes) breaks the packer.

TODO:
 - update tests
 - documentation
 - consider adding a length constraint to the origin type to prevent accidents

### CODE REVIEW

**Comment by fractalcat** [comment]
Huh, tests pass. Contents telemetry now works. More integration tests + documentation, and probably add a NamespacedOrigin type separate from the Origin type.

**Comment by fractalcat** [comment]
I think this is ready for review/merge now. @tranma @christian-marie @afcowie

**Comment by fractalcat** [comment]
Just realised I'd forgotten the integration test. Ran it, it's passing too. (We should really automate that.)

**Comment by christian-marie** [comment]
Looks good. As a matter of readability, these days I tend to do something like this:

```haskell
data ThingOption = OptionA | OptionB

f :: ThingOption -> String
f OptionA = undefined
f OptionB = undefined
```

As this makes it very clear what's going on, as opposed to true/false.

**Comment by christian-marie** [comment]
Feel free to merge with or without this.

**Comment by fractalcat** [comment]
Good point. Updated.

**Pull request merged**
